version: '3'
services:
  php:
    container_name: php
    image: testx
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/html:cached
      - ./vendor:/var/www/html/vendor:cached
      - ./var:/var/www/html/var
  mysql:
    image: mysql:5.7.23
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: hello
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: topsecret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - mysql_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/data

volumes:
  mysql_data:
  rabbitmq_data:
  vendor:
  var: